In [1]:
import numpy
numpy.__version__

'1.15.0'

In [2]:
import numpy as np

NumPy arrays contain values of a single type.

### Arrays
The Numpy array is fixed-type data container.

In [3]:
# Arrays can be created from lists
np.array([9, 7, 8, 5])

array([9, 7, 8, 5])

In [4]:
# If there are different types in the list, Numpy upcasts
np.array([1, 7.89, 5])

array([1.  , 7.89, 5.  ])

In [5]:
# setting the data type explicitly
np.array([9,7,8,5], dtype='float64')

array([9., 7., 8., 5.])

In [6]:
# one-dimensional array containing only ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [7]:
# Two-dimensional array containing only zeros
np.zeros((2, 3), dtype=float)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
# Fill a two-dimensional array with a specific number
np.full((2, 3), 7.89)

array([[7.89, 7.89, 7.89],
       [7.89, 7.89, 7.89]])

In [9]:
# A sequence starting from 0 to 12 with increment of 3
np.arange(0, 12, 3)

array([0, 3, 6, 9])

In [10]:
# Equally spaced values of 6 numbers between 0 and 1
np.linspace(0, 1, 6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [12]:
# Two-dimensional array of random numbers from a uniform distribution on [0,1]
np.random.random((2, 3))

array([[0.40267466, 0.55301835, 0.11571176],
       [0.54780745, 0.14233346, 0.85935087]])

In [13]:
# Two-dimensional array of random numbers from  a normal distribution with mean=0 and standard deviation = 1
np.random.normal(0, 1, (2, 3))

array([[-0.2692481 ,  1.89958085,  0.81193848],
       [-0.66761438,  0.1435711 , -2.07030664]])

In [14]:
# Two-dimensional array of random integers in the interval [0, 20)
np.random.randint(0, 20, (2, 3))

array([[ 1,  3, 12],
       [ 4,  9, 13]])

In [15]:
# The four-dimensional identity matrix 
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Array attributes

In [16]:
 # Reproducibility
np.random.seed(0) 
a1 = np.random.randint(10, size=5) 
a1

array([5, 0, 3, 3, 7])

In [17]:
np.random.seed(0)
a2 = np.random.randint(0, 10, 5)
a2

array([5, 0, 3, 3, 7])

In [18]:
# A three-dimensional array
a3 = np.random.randint(10, size=(2, 3, 4))
a3


array([[[9, 3, 5, 2],
        [4, 7, 6, 8],
        [8, 1, 6, 7]],

       [[7, 8, 1, 5],
        [9, 8, 9, 4],
        [3, 0, 3, 5]]])

In [19]:
# The attributes of the 3-dim array a3
print("a3 ndim: ", a3.ndim)
print("a3 shape:", a3.shape)
print("a3 size: ", a3.size)

a3 ndim:  3
a3 shape: (2, 3, 4)
a3 size:  24


In [20]:
# The dat type of the content
a3.dtype

dtype('int32')

In [21]:
# The bytes of each item(element) and the total bytes of the array
print("itemsize:", a3.itemsize, "bytes")
print("totalbytes:", a3.nbytes, "bytes")

itemsize: 4 bytes
totalbytes: 96 bytes


### Indices of arrays

In [26]:
# Similar to indices of lists. counting starts from zero
a1



array([5, 0, 3, 3, 7])

In [27]:
a1[0]

5

In [28]:
a1[4]

7

In [29]:
a1[-1]

7

In [30]:
# Indices of a two-dimensional array
a2 = np.random.randint(10, size=(2, 3))  
a2

array([[0, 2, 3],
       [8, 1, 3]])

In [31]:
a2[0,0]

0

In [32]:
a2[1,2]

3

In [33]:
a2[-1,-1]

3

In [34]:
# Assign values. Note that a different type will be converted since arrays are fixed-type
a2[1,2] = 100.89
a2

array([[  0,   2,   3],
       [  8,   1, 100]])

### Slicing arrays

In [35]:
# slice of a is a[start:stop:step]
#default start=0, stop=size of dimension, step=1.

a = np.arange(8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [36]:
a[:2]

array([0, 1])

In [37]:
a[2:]

array([2, 3, 4, 5, 6, 7])

In [38]:
a[1:4]

array([1, 2, 3])

In [39]:
a[::3] # takes step size of 3

array([0, 3, 6])

In [40]:
a[2::3] # takes step size of 3 starting at 2

array([2, 5])

In [41]:
# negative step value means exchanging start and stop
a[::-1]

array([7, 6, 5, 4, 3, 2, 1, 0])

In [42]:
a[6::-2]

array([6, 4, 2, 0])

In [43]:
# 2-dim array
b = np.random.randint(0, 10, (4, 5))
b

array([[3, 3, 7, 0, 1],
       [9, 9, 0, 4, 7],
       [3, 2, 7, 2, 0],
       [0, 4, 5, 5, 6]])

In [44]:
# First two rows and first 3 columns
c = b[:2, :3] 
c

array([[3, 3, 7],
       [9, 9, 0]])

In [45]:
# If you chance an element of subarray c , then the array b changes too. c is not copy of b
c[1,2] = 555
print(c)


[[  3   3   7]
 [  9   9 555]]


In [46]:
# Check if b changed too
b 

array([[  3,   3,   7,   0,   1],
       [  9,   9, 555,   4,   7],
       [  3,   2,   7,   2,   0],
       [  0,   4,   5,   5,   6]])

In [47]:
# To get a copy of b
c_copy = b[:2, :3].copy()
c_copy[0,0] = 777
c_copy

array([[777,   3,   7],
       [  9,   9, 555]])

In [48]:
# But b did not change
b

array([[  3,   3,   7,   0,   1],
       [  9,   9, 555,   4,   7],
       [  3,   2,   7,   2,   0],
       [  0,   4,   5,   5,   6]])

In [56]:
# only first column
b[:,0]

array([3, 9, 3, 0])

In [57]:
# only first row
b[0,:]

array([3, 3, 7, 0, 1])

In [58]:
# Equivalently
b[0]

array([3, 3, 7, 0, 1])

In [59]:
# 3-dim array
a3

array([[[9, 3, 5, 2],
        [4, 7, 6, 8],
        [8, 1, 6, 7]],

       [[7, 8, 1, 5],
        [9, 8, 9, 4],
        [3, 0, 3, 5]]])

In [60]:
a3[0]

array([[9, 3, 5, 2],
       [4, 7, 6, 8],
       [8, 1, 6, 7]])

In [61]:
a3[1,1,1]

8

In [62]:
a3[:,1,:]

array([[4, 7, 6, 8],
       [9, 8, 9, 4]])

In [ ]:
### Reshape

In [63]:
# Recall the array a
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [64]:
a.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [65]:
a.reshape(1,8)

array([[0, 1, 2, 3, 4, 5, 6, 7]])

In [66]:
a.reshape(8,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

### Concatenate

In [67]:
np.concatenate([a, a])

array([0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7])

In [68]:
np.concatenate([a2, a2])

array([[  0,   2,   3],
       [  8,   1, 100],
       [  0,   2,   3],
       [  8,   1, 100]])

In [69]:
np.concatenate([a2, a2], axis = 1)

array([[  0,   2,   3,   0,   2,   3],
       [  8,   1, 100,   8,   1, 100]])

### Universal functions


In [70]:
# A vectorized operation is done on each element of an array
print("a + 1 =", a + 1)
print("a ** 2 = ", a ** 2)

a + 1 = [1 2 3 4 5 6 7 8]
a ** 2 =  [ 0  1  4  9 16 25 36 49]


In [71]:
np.add(a,1)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [72]:
-a

array([ 0, -1, -2, -3, -4, -5, -6, -7])

In [73]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ])

In [74]:
np.exp(a) # np.exp2(a) or np.power(7,a), i.e., 7**a

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03])

In [75]:
np.log(a) # np.log2(a) or np.log10(a)

C:\Users\i803035\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015])

In [76]:
# Sum of elements
np.sum(a) # you can use array methods a.sum()


28

In [77]:
print(np.max(a))
np.min(a)

7


0

In [78]:
# mean and standard deviation
print(a.mean())
a.std()

3.5


2.29128784747792

In [79]:
# Recall a2
a2

array([[  0,   2,   3],
       [  8,   1, 100]])

In [80]:
# sum of all the elements
a2.sum() # or np.sum(a2)  


114

In [81]:
a2.sum(axis = 0)  # collapsing rows

array([  8,   3, 103])

In [82]:
a2.sum(axis = 1)  # collapsing columns

array([  5, 109])

### Broadcasting

In [83]:
# We had already a + 1. Since the scalar 1 is zero-dim, it is broadcasted to [1,1,1,1,1,1,1,1]
# Now for higher-dim, let us introduce x and add to a2
x = np.full(3, 8)
x


array([8, 8, 8])

In [84]:
a2 

array([[  0,   2,   3],
       [  8,   1, 100]])

In [85]:
a2 + x

array([[  8,  10,  11],
       [ 16,   9, 108]])

In [86]:
y = np.full(2, 8).reshape(2,1)
y

array([[8],
       [8]])

In [87]:
a2 + y

array([[  8,  10,  11],
       [ 16,   9, 108]])

### Mean-centering of 2D array


In [89]:
z = np.random.random((5, 2))
z_mean = z.mean(0) # collapsing rows axis = 0 to calculate the column means
print(z)
z_mean

[[0.35815217 0.75068614]
 [0.60783067 0.32504723]
 [0.03842543 0.63427406]
 [0.95894927 0.65279032]
 [0.63505887 0.99529957]]


array([0.51968328, 0.67161946])

In [90]:
z_mean_centered = z - z_mean
z_mean_centered.mean() # close to zero


5.551115123125783e-17

### Boolean Comparisons and Masks

In [91]:
a < 5

array([ True,  True,  True,  True,  True, False, False, False])

In [92]:
a >= 6

array([False, False, False, False, False, False,  True,  True])

In [93]:
(a < 7) & (a > 4)

array([False, False, False, False, False,  True,  True, False])

In [94]:
a2 == 100

array([[False, False, False],
       [False, False,  True]])

In [95]:
# Count number of elements less than 5
np.count_nonzero(a < 5)

5

In [ ]:
# Equivalent
np.sum( a < 5) # since False = 0 and True = 1

In [ ]:
a2

In [ ]:
np.sum(a2 < 5, axis=1) # collapse columns, i.e., how many elements less than 5 in each row

In [ ]:
np.any(a > 7)

In [ ]:
np.all(a < 8)

In [ ]:
# Masks
a[a < 5]

### Sorting

In [ ]:
uns = np.array([7,1,6,4,5])
uns

In [ ]:
np.sort(uns)

In [ ]:
uns.sort() # It sorts the array in-place
uns

In [ ]:
# The indices of the sorted elements
uns2 = np.array([7,1,6,4,5])
indices = uns2.argsort()
indices

In [ ]:
uns2[indices]

In [ ]:
a2

In [ ]:
np.sort(a2, axis =0) # collapse rows,i.e., sort each column

In [ ]:
np.sort(a2, axis =1) # collapse columns,i.e., sort each row

In [ ]:
import matplotlib as mpl
import matplotlib.pyplot as plt
plt.style.use('classic')
%matplotlib

import numpy as np

x = np.linspace(0, 10, 100)

plt.plot(x, np.sin(x))
plt.plot(x, np.cos(x))