In [1]:
# check pandas version
import pandas
pandas.__version__

'0.22.0'

In [2]:
# alias pd
import pandas as pd


### Pandas data objects: Series, DataFrame, and Index.
Numpy rows and columns are identified by integer indices; Pandas uses labels

#### Series

In [4]:
# Series as one-dimensional indexed array
s1 = pd.Series([5, 3, 1])
s1

0    5
1    3
2    1
dtype: int64

In [5]:
print(s1.index)
s1.values

RangeIndex(start=0, stop=3, step=1)


array([5, 3, 1], dtype=int64)

In [6]:
s1[1] # no different than Numpy array with the usual index

3

In [7]:
s2 = pd.Series([5, 3, 1], index = ['first', "second", 'third'])
s2

first     5
second    3
third     1
dtype: int64

In [8]:
s2['second'] # accessing like in a dictionary

3

In [9]:
s2["first":"third"]

first     5
second    3
third     1
dtype: int64

In [10]:
# Series from a dictionary
s3 = pd.Series({"first":1, 2:"second"})
s3

first         1
2        second
dtype: object

#### DataFrame

In [11]:
# A Series is like a one-dimensional array with flexible indices, 
# A DataFrame is like a two-dimensional array with  flexible row indices and column names.

s4 = pd.Series([7,1,5,3], index = ['person1', 'person2', 'person3', 'person4'])
s5 = pd.Series([9,4,11,8], index = ['person1', 'person2', 'person3', 'person4'])
df1 =  pd.DataFrame({'Age': s4, 'Weight': s5}) # a dataFrame as a dictionary of Series structures having same index
df1

Age  Weight
person1    7       9
person2    1       4
person3    5      11
person4    3       8

In [12]:
print(df1.index)
print(df1.columns)
df1['Age']

Index(['person1', 'person2', 'person3', 'person4'], dtype='object')
Index(['Age', 'Weight'], dtype='object')


person1    7
person2    1
person3    5
person4    3
Name: Age, dtype: int64

### Data Selection: loc and iloc

In [13]:
# Series
list(s2.items())

[('first', 5), ('second', 3), ('third', 1)]

In [14]:
s6 = pd.Series(['a', 'b', 'c'], index=[2, 3, 4])
s6

2    a
3    b
4    c
dtype: object

In [15]:
s6[2] # explicit index of the series

'a'

In [18]:
# slicing uses the implicit index
s6[2:]


4    c
dtype: object

In [19]:
s6.loc[2:] # slicing with loc uses the explicit index

2    a
3    b
4    c
dtype: object

In [20]:
s6.loc[2]

'a'

In [23]:
# iloc for the implicit index
s6.iloc[2]
type(s6.iloc[2])

str

In [24]:
s6.iloc[2:]
type(s6.iloc[2:])

pandas.core.series.Series

In [25]:
df1.Age # same as df1["Age]

person1    7
person2    1
person3    5
person4    3
Name: Age, dtype: int64

In [29]:
df1.values
df1.keys

<bound method NDFrame.keys of          Age  Weight
person1    7       9
person2    1       4
person3    5      11
person4    3       8>

In [30]:
df1.T # Transpose

person1  person2  person3  person4
Age           7        1        5        3
Weight        9        4       11        8

In [31]:
# You get a row when you pass  a single index to an array 
df1.values[1]

array([1, 4], dtype=int64)

In [32]:
# You get a column if you pass a single label to a DataFrame 
df1["Age"]

person1    7
person2    1
person3    5
person4    3
Name: Age, dtype: int64

In [33]:
# implit index with iloc
df1.iloc[:2,:1 ]

Age
person1    7
person2    1

In [34]:
# explicit index and column names with loc
df1.loc[:'person2', :'Weight'] # unlike the implicit, the last is included

Age  Weight
person1    7       9
person2    1       4

In [35]:
# We have seen the indexing is used for columns, e.g., df1['Age']. However, slicing is for rows
df1["person1":'person3']

Age  Weight
person1    7       9
person2    1       4
person3    5      11

In [36]:
df1[0:3] # using implicit row numbers

Age  Weight
person1    7       9
person2    1       4
person3    5      11

In [37]:
# Masking refers to rows
df1[df1.Age > 1]

Age  Weight
person1    7       9
person3    5      11
person4    3       8

### Missing Values

In [42]:
# Python has None object:
import numpy as np
R1 = np.array([4, None, 5])
R1 # An array has only one data type. Here dtype=object is the common type

array([4, None, 5], dtype=object)

In [43]:
#  NaN ( Not a Number) is a special floating-point value by the standard IEEE 
R2 = np.array([4, np.nan, 5])
print(R2)
R2.dtype

[ 4. nan  5.]


dtype('float64')

In [44]:
print(5 + np.nan)
print(5*np.nan)
print(R2.sum())
np.nansum(R2)  # ignore NaN

nan
nan
nan


9.0

In [45]:
# Pandas
s7 = pd.Series([5, np.nan, 7, None]) #  upcast to a floating-point type to consider the NA
s7

0    5.0
1    NaN
2    7.0
3    NaN
dtype: float64

In [46]:
s7.isnull() 

0    False
1     True
2    False
3     True
dtype: bool

In [47]:
s7[s7.notnull()]

0    5.0
2    7.0
dtype: float64

In [48]:
# dropping NAs
s7.dropna()

0    5.0
2    7.0
dtype: float64

In [49]:
# NAs in data frames
df2 = pd.DataFrame([[5, 7, 2],
                   [9,  np.nan,  1],
                   [3,      8, np.nan]])
df2

0    1    2
0  5  7.0  2.0
1  9  NaN  1.0
2  3  8.0  NaN

In [50]:
# You can drop rows or columns, not single values
df2.dropna() # default is row-wise

0    1    2
0  5  7.0  2.0

In [51]:
df2.dropna(axis =1) #column-wise. 
#Also, how = 'any' is default. how = 'all' drops when all elements of a column are null

0
0  5
1  9
2  3

In [52]:
# Filling NAs
df2.fillna(0)

0    1    2
0  5  7.0  2.0
1  9  0.0  1.0
2  3  8.0  0.0

In [53]:
print(df2.fillna(method='ffill')) # forward 
print(df2.fillna(method='bfill', axis =1)) #backward
df2

   0    1    2
0  5  7.0  2.0
1  9  7.0  1.0
2  3  8.0  1.0
     0    1    2
0  5.0  7.0  2.0
1  9.0  1.0  1.0
2  3.0  8.0  NaN


0    1    2
0  5  7.0  2.0
1  9  NaN  1.0
2  3  8.0  NaN

### Aggregation

In [54]:
df = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar', 'foo', 'bar', 'foo', 'foo'],
                   'B' : ['one', 'one', 'two', 'three', 'two', 'two', 'one', 'three'],
                   'C' : np.random.randn(8),
                   'D' : np.random.randn(8)})
    

In [55]:
df

A      B         C         D
0  foo    one -0.335565 -0.701208
1  bar    one -0.939917 -1.787650
2  foo    two  0.297708  0.669731
3  bar  three  0.183790 -0.465553
4  foo    two -0.162864 -0.367747
5  bar    two -0.607434 -1.735574
6  foo    one  1.058220  1.784998
7  foo  three  0.275072 -0.027988

In [56]:
grouped = df.groupby('A')

grouped

In [114]:
grouped.sum() # df.groupby('A').sum()

C         D
A                      
bar -3.230205  1.613101
foo -0.306538  2.020065

In [115]:
df.groupby('A').get_group('foo')

A      B         C         D
0  foo    one -0.482049  0.438517
2  foo    two -0.435905  0.443399
4  foo    two -0.012269  1.126415
6  foo    one  0.283217 -0.715370
7  foo  three  0.340468  0.727104

In [61]:
grouped.agg(np.sum)

C         D
A                      
bar -1.363562 -3.988777
foo  1.132572  1.357786

In [117]:
grouped.size()

A
bar    3
foo    5
dtype: int64

In [75]:
grouped.describe()
pandas.DataFrame.describe?

In [76]:
# Multiple functions
grouped['C'].agg([np.sum, np.mean, np.std])

sum      mean       std
A                                
bar -1.363562 -0.454521  0.577249
foo  1.132572  0.226514  0.540072

### Reading Data Files into Pandas
Reference: (http://nbviewer.jupyter.org/github/justmarkham/pandas-videos/blob/master/pandas.ipynb)

In [77]:
# tab-seperated data into pandas data frame. the data is Chipotle orders
orders = pd.read_table('http://bit.ly/chiporders')

In [78]:
orders.head()  # head is a method

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   

                                  choice_description item_price  
0                                                NaN     $2.39   
1                                       [Clementine]     $3.39   
2                                            [Apple]     $3.39   
3                                                NaN     $2.39   
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98

In [79]:
pd.read_table?

In [80]:
# Let us read data on movie users. It is seperated by a pipe
users = pd.read_table('http://bit.ly/movieusers')

In [81]:
users.head()

1|24|M|technician|85711
0       2|53|F|other|94043
1      3|23|M|writer|32067
2  4|24|M|technician|43537
3       5|33|F|other|15213
4   6|42|M|executive|98101

In [82]:
# The first row is read as column names
users = pd.read_table('http://bit.ly/movieusers', sep='|')
users.head()

1  24  M  technician  85711
0  2  53  F       other  94043
1  3  23  M      writer  32067
2  4  24  M  technician  43537
3  5  33  F       other  15213
4  6  42  M   executive  98101

In [83]:
users = pd.read_table('http://bit.ly/movieusers', sep='|', header=None)
users.head()

0   1  2           3      4
0  1  24  M  technician  85711
1  2  53  F       other  94043
2  3  23  M      writer  32067
3  4  24  M  technician  43537
4  5  33  F       other  15213

In [84]:
user_cols = ['user_id', 'age', 'gender', 'occupation', 'zip_code']
users = pd.read_table('http://bit.ly/movieusers', sep='|', header=None, names=user_cols)
users.head()

user_id  age gender  occupation zip_code
0        1   24      M  technician    85711
1        2   53      F       other    94043
2        3   23      M      writer    32067
3        4   24      M  technician    43537
4        5   33      F       other    15213

In [85]:
users['occupation']

0         technician
1              other
2             writer
3         technician
4              other
5          executive
6      administrator
7      administrator
8            student
9             lawyer
10             other
11             other
12          educator
13         scientist
14          educator
15     entertainment
16        programmer
17             other
18         librarian
19         homemaker
20            writer
21            writer
22            artist
23            artist
24          engineer
25          engineer
26         librarian
27            writer
28        programmer
29           student
           ...      
913            other
914    entertainment
915         engineer
916          student
917        scientist
918            other
919           artist
920          student
921    administrator
922          student
923            other
924         salesman
925    entertainment
926       programmer
927          student
928        scientist
929        sc

In [86]:
users.occupation

0         technician
1              other
2             writer
3         technician
4              other
5          executive
6      administrator
7      administrator
8            student
9             lawyer
10             other
11             other
12          educator
13         scientist
14          educator
15     entertainment
16        programmer
17             other
18         librarian
19         homemaker
20            writer
21            writer
22            artist
23            artist
24          engineer
25          engineer
26         librarian
27            writer
28        programmer
29           student
           ...      
913            other
914    entertainment
915         engineer
916          student
917        scientist
918            other
919           artist
920          student
921    administrator
922          student
923            other
924         salesman
925    entertainment
926       programmer
927          student
928        scientist
929        sc

In [87]:
users.shape # attributes have no parenthesis

(943, 5)

In [88]:
users.dtypes

user_id        int64
age            int64
gender        object
occupation    object
zip_code      object
dtype: object

In [89]:
users.describe()

user_id         age
count  943.000000  943.000000
mean   472.000000   34.051962
std    272.364951   12.192740
min      1.000000    7.000000
25%    236.500000   25.000000
50%    472.000000   31.000000
75%    707.500000   43.000000
max    943.000000   73.000000

In [92]:
users.describe(include='all')

user_id         age gender occupation zip_code
count   943.000000  943.000000    943        943      943
unique         NaN         NaN      2         21      795
top            NaN         NaN      M    student    55414
freq           NaN         NaN    670        196        9
mean    472.000000   34.051962    NaN        NaN      NaN
std     272.364951   12.192740    NaN        NaN      NaN
min       1.000000    7.000000    NaN        NaN      NaN
25%     236.500000   25.000000    NaN        NaN      NaN
50%     472.000000   31.000000    NaN        NaN      NaN
75%     707.500000   43.000000    NaN        NaN      NaN
max     943.000000   73.000000    NaN        NaN      NaN

In [95]:
# UFO reports data seperated by comma
ufo = pd.read_table('http://bit.ly/uforeports', sep=',')

# read_csv has default comma as seperator
ufo = pd.read_csv('http://bit.ly/uforeports')

In [97]:
# ufo.Location = ufo.City + ', ' + ufo.State will not work

# You have to use bracket notation to define the Series name)
ufo['Location'] = ufo.City + ', ' + ufo.State
ufo.shape

(18241, 6)

In [136]:
ufo.State.value_counts()

CA    2529
WA    1322
TX    1027
NY     914
FL     837
AZ     738
OH     667
IL     613
PA     598
MI     591
OR     534
MO     448
NJ     370
CO     367
WI     357
NC     356
IN     326
GA     325
MA     322
VA     299
TN     286
NV     284
MN     254
KY     244
NM     241
CT     225
MD     215
AR     206
UT     193
AL     193
OK     193
ME     181
KS     176
LA     174
SC     166
IA     162
MT     144
MS     139
WV     132
ID     130
NH     125
AK     116
NE     101
HI      85
WY      69
RI      67
SD      57
ND      51
VT      44
DE      43
Fl       4
Ca       1
Name: State, dtype: int64

In [98]:
ufo["Shape Reported"].unique()

array(['TRIANGLE', 'OTHER', 'OVAL', 'DISK', 'LIGHT', 'CIRCLE', 'CIGAR',
       'CYLINDER', 'FIREBALL', 'SPHERE', nan, 'RECTANGLE', 'FORMATION',
       'FLASH', 'CHEVRON', 'EGG', 'CONE', 'DIAMOND', 'VARIOUS',
       'TEARDROP', 'CROSS', 'DELTA', 'ROUND', 'DOME', 'PYRAMID',
       'CRESCENT', 'FLARE', 'HEXAGON'], dtype=object)

In [99]:
ufo["Shape Reported"].value_counts()

LIGHT        2803
DISK         2122
TRIANGLE     1889
OTHER        1402
CIRCLE       1365
SPHERE       1054
FIREBALL     1039
OVAL          845
CIGAR         617
FORMATION     434
VARIOUS       333
RECTANGLE     303
CYLINDER      294
CHEVRON       248
DIAMOND       234
EGG           197
FLASH         188
TEARDROP      119
CONE           60
CROSS          36
DELTA           7
ROUND           2
CRESCENT        2
DOME            1
HEXAGON         1
PYRAMID         1
FLARE           1
Name: Shape Reported, dtype: int64